### ISSUE TITLE
Make sure you can update the address of the group. 

### ISSUE THREAD

**Issue by corsacca** [ChasmSolutions/zume-project-multilingual#13]
right now it gets randomized

**Comment by ChrisChasm** [comment]
Where is it randomized? Can you add a screenshot?

**Comment by corsacca** [comment]
![image](https://user-images.githubusercontent.com/24901539/34109710-bd1a1140-e404-11e7-904e-a2d76b3ffb1d.png)
I entered the letter "a" as the address. I saved and then it changed to an address in germany.
I know "a" is not an address. I'm guessing this is google doing it's best guess.
Maybe we can :
- save google's guess as a second field
- provide more visual feedback for address selection (like an amazon when set your shipping address)
I'm not sure google will be great at guessing addresses across the world.

**Comment by ChrisChasm** [comment]
ea4f79a749f0354884e1686985405920924bc705
ea74fc983f7e6be124bc6b0ebe93a1a2627e05b5
eea3c84aca82990f11e9f08e2ba505a2fe3569d5
320fa9ad1e27506840f0834f81adcb1a8535b164
5d0117211372c9b9d5527f295ff396ba68cf8a04
