### ISSUE TITLE
the `Tools You've Gained` section on the dashboard gets erased when you complete session 10

### ISSUE THREAD

**Issue by corsacca** [ChasmSolutions/zume-project-multilingual#17]

**Comment by ChrisChasm** [comment]
Is this a question? 
I know I was thinking that once you have completed the training with one group, you would see all the tools from there forward. That's at least how it is coded now.

**Comment by corsacca** [comment]
![screenshot from 2017-12-18 14-29-43](https://user-images.githubusercontent.com/24901539/34108323-ed17952a-e3ff-11e7-9d00-334229497b9b.png)

**Comment by ChrisChasm** [comment]
Fixed: 
https://github.com/ChasmSolutions/zume-project-multilingual/commit/76c4eef639bc09c45e7a9dbb745917bc4584fc83
